#######################################################
# 
# Test.py
# Python implementation of the Class Test
# Generated by Enterprise Architect
# Created on:      16-3ÔÂ-2023 10:05:08
# Original author: dll
# 
#######################################################


class Test:
    def main(args):
        	TSP tsp = new TSP();
        	tsp.eaTSP();
        	tsp.elevenStepOutputResult()