#######################################################
# 
# TSP.py
# Python implementation of the Class TSP
# Generated by Enterprise Architect
# Created on:      16-3月-2023 10:05:08
# Original author: dll
# 
#######################################################


class TSP:
    # 用于存储两个城市之间的距离
    __D = {{0,2,6,5},{2,0,4,4},{6,4,0,2},{5,4,2,0}}
    # 保证Dtemp比任意两个城市之间的距离都大（算法描述中的无穷大）
    __Dtemp = Integer.MAX_VALUE
    # 城市结点个数
    __N = 4
    # 用于存储已访问过的城市
    __S = {0,0,0,0}
    # 用于记算已访问过的城市的最小路径长度
    __Sum = 0
    def eaTSP():
        pass

    def elevenStepOutputResult():
        pass

    def fiveStepAlternate(I):
        """Begin - EA generated code for  Activities and Interactions
        """
        pass