#######################################################
# 
# Fibonacci.py
# Python implementation of the Class Fibonacci
# Generated by Enterprise Architect
# Created on:      16-3ÔÂ-2023 10:04:14
# Original author: dll
# 
#######################################################
from ADA01DynamicProgramming.int[] import int[]

class Fibonacci:
    def b2uFibonacci(n):
        pass

    def memFib(n, Memo):
        pass

    def memFibonacci(n):
        """Begin - EA generated code for  Activities and Interactions
        """
        pass

    def recFibonacci(n):
        pass