#######################################################
# 
# int.py
# Python implementation of the Class int
# Generated by Enterprise Architect
# Created on:      16-3ÔÂ-2023 10:04:14
# Original author: dll
# 
#######################################################


class int:
    pass