#######################################################
# 
# Test.py
# Python implementation of the Class Test
# Generated by Enterprise Architect
# Created on:      16-3ÔÂ-2023 10:04:14
# Original author: dll
# 
#######################################################


class Test:
    def main(args):
        Fibonacci fib=new Fibonacci();
        System.out.println(fib.recFibonacci(6));
        System.out.println(fib.memFibonacci(6));
    
        	
        YachtRent yr = new YachtRent();
        yr.testYachtRent();