#######################################################
# 
# YachtRent.py
# Python implementation of the Class YachtRent
# Generated by Enterprise Architect
# Created on:      16-3ÔÂ-2023 10:04:14
# Original author: dll
# 
#######################################################

import java.util.Scanner;

class YachtRent:
    def printResult(i, j, s):
        """Begin - EA generated code for  Activities and Interactions
        """
        pass

    def testYachtRent():
        pass

    def yachtRent(m, s, n):
        pass