# encoding=utf-8
#######################################################
# 
# Test.py
# Python implementation of the Class Test
# Generated by Enterprise Architect
# Created on:      16-3��-2023 14:43:28
# Original author: dll
# 
#######################################################
from os import system

from QuickSort import QuickSort


class Test:
    def printa(self, a):
        stra = "["
        for x in a:
            stra += str(x) + ", "
        stra += "]"
        stra = stra.replace(", ]", "]")
        print(stra)

    def test_main(self):
        qs = QuickSort()
        a = [3, 2, 1, 4, 5, 6, 9, 8, 7]
        print("Original Array a[]:")
        self.printa(a)

        qs.quickSort(a)
        print("Sorted   Array a[]:")
        self.printa(a)


test = Test()
test.test_main()
system("pause")
