#######################################################
# 
# Bird.py
# Python implementation of the Class Bird
# Generated by Enterprise Architect
# Original author: liu dongliang
# 
#######################################################
from Wing import Wing
from Animal import Animal
from Water import Water
from Oxygen import Oxygen


class Bird(Animal):
    __rWing: Wing
    __lWing: Wing

    def __init__(self):
        lWing = Wing(" left wing");
        rWing = Wing(" right wing");
        print("Bird have Two Wings!")

    def metabolize(self, o, w):
        print("bird Depends on Oxygen and Water: parameters of metabolize");

    def propagate(self):
        print("Bird egg 5g");
