#######################################################
# 
# Bird.py
# Python implementation of the Class Bird
# Generated by Enterprise Architect
# Original author: liu dongliang
# 
#######################################################
from Wing import Wing
from Animal import Animal
from Water import Water
from Oxygen import Oxygen

class Bird(Animal):

    m_lWing: Wing
    m_rWing: Wing

    def Bird(self):
        m_lWing= Wing(" left wing\n");
        m_rWing= Wing(" right wing\n");

    def metabolize(self, o, w):
        print("bird Depends on Oxygen and Water\n");
	
    def propagate(self):
        print("Bird egg 5g\n");