#######################################################
# 
# ClimateType.py
# Python implementation of the Enumeration ClimateType
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:16
# Original author: The Administrator
# 
#######################################################
from enum import Enum


class ClimateType(Enum):
    coldzone = 1
    temperatezone = 2
    torridzone = 3
