#######################################################
# 
# DonaldDuck.py
# Python implementation of the Class DonaldDuck
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:16
# Original author: liu dongliang
# 
#######################################################
from Duck import Duck
from Speak import Speak


class DonaldDuck(Speak):
    duck: Duck  # Duck

    def DonaldDuck(self):
        pass

    def setduck(self, d):
        self.duck = d

    @staticmethod
    def quackSpeak():
        print("staticmethod");

    def speak(self):
        print("personification");
