#######################################################
# 
# DonaldDuck.py
# Python implementation of the Class DonaldDuck
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:16
# Original author: liu dongliang
# 
#######################################################
from Duck import Duck
from Speak import Speak


class DonaldDuck(Speak):
    m_Duck: Duck  # Duck

    def DonaldDuck(self):
        pass

    def setm_duck(self, d):
        self.m_Duck = d

    @staticmethod
    def quackSpeak():
        print("staticmethod\n");

    def speak(self):
        print("personification\n");
