#######################################################
# 
# Duck.py
# Python implementation of the Class Duck
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:16
# Original author: liu dongliang
# 
#######################################################
from Bird import Bird


class Duck(Bird):

    def Duck(self):
        print("my is a Duck\n");

    def propagate(self):
        print("duck egg 70g\n");

    def quack(self):
        print("Duck Quack\n");
