#######################################################
# 
# Fly.py
# Python implementation of the Interface Fly
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:16
# Original author: liu dongliang
# 
#######################################################
from abc import ABCMeta, abstractmethod

class Fly(metaclass=ABCMeta):

    @abstractmethod
    def fly(self):
        pass