#######################################################
# 
# Oxygen.py
# Python implementation of the Class Oxygen
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:16
# Original author: liu dongliang
# 
#######################################################


class Oxygen:

    def Oxygen(self):
        print("Depends on Oxygen\n");