#######################################################
# 
# Penguin.py
# Python implementation of the Class Penguin
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:17
# Original author: liu dongliang
# 
#######################################################
from Climate import Climate
from Bird import Bird


class Penguin(Bird):
    m_Climate: Climate

    def propagate(self):
        print("Penguin Egg 500g\n");

    def Penguin(self):
        print("my is a Penguin\n");

    def setM_Climate(self, c):
        self.m_Climate = c;
        print("Penguin living  Climate:" + self.m_Climate.toString());
