#######################################################
# 
# Penguin.py
# Python implementation of the Class Penguin
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:17
# Original author: liu dongliang
# 
#######################################################
from Climate import Climate
from Bird import Bird


class Penguin(Bird):

    climate: Climate

    def __init__(self):
        print("my is a Penguin");

    def setclimate(self, c):
        self.climate = c;
        print("Penguin living  Climate:" + self.climate.toString());

    def propagate(self):
        print("propagate: Penguin Egg 500g");