#######################################################
# 
# Speak.py
# Python implementation of the Interface Speak
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:17
# Original author: liu dongliang
# 
#######################################################
from abc import ABCMeta, abstractmethod


class Speak(metaclass=ABCMeta):

    @abstractmethod
    def speak(self):
        pass
