######self=None########################################
# 
# Water.py
# Python implementation of the Class Water
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:17
# Original author: liu dongliang
# 
#######################################################


class Water:

    def __init__(self):
        print("my is water");
