#######################################################
# 
# WildGeeseGroup.py
# Python implementation of the Class WildGeeseGroup
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:17
# Original author: liu dongliang
# 
#######################################################
import sys

from WildGoose import WildGoose


class WildGeeseGroup:
    count = 3

    wildGeese = []

    def joinWildGeeseGroup(self, wg):
        self.count += 1
        print("joinWildGeeseGroup has " + str(self.count) + " WildGeese!");
        if self.count < sys.maxsize:
            self.wildGeese.append(wg);

        else:
            print("WildGeeseGroup Too Big");

    def leaveWildGeeseGroup(self, wg):
        self.count -= 1
        print("A WildGeese leaved. " + str(self.count) + " WildGeese!");
        self.wildGeese.remove(wg);

    def __init__(self, wgs):
        print("WildGeeseGroup Total WildGeese " + str(sys.maxsize))
        for i in range(0, len(wgs)):
            self.wildGeese.append(wgs[i])
        print("WildGeeseGroup initial size " + str(len(wgs)));
