#######################################################
# 
# Wing.py
# Python implementation of the Class Wing
# Generated by Enterprise Architect
# Created on:      03-03-2023 8:55:17
# Original author: liu dongliang
# 
#######################################################


class Wing:

    def __init__(self, lr):
        print("my " + lr);
